CREATE TABLESPACE BABYFISH_DISTINCT_LIMIT_DATA
    LOGGING
    DATAFILE ' BABYFISH_DISTINCT_LIMIT_DATA.DBF' 
    SIZE 32M 
    AUTOEXTEND ON 
    NEXT 32M MAXSIZE 2048M
    EXTENT MANAGEMENT LOCAL;

CREATE TEMPORARY TABLESPACE BABYFISH_DISTINCT_LIMIT_TEMP
    TEMPFILE ' BABYFISH_DISTINCT_TEMP_DATA.DBF' 
    SIZE 32M 
    AUTOEXTEND ON 
    NEXT 32M MAXSIZE 2048M
    EXTENT MANAGEMENT LOCAL;
    
CREATE USER BABYFISH_DISTINCT_LIMIT
    IDENTIFIED BY 123
    DEFAULT TABLESPACE BABYFISH_DISTINCT_LIMIT_DATA
    TEMPORARY TABLESPACE BABYFISH_DISTINCT_LIMIT_TEMP;
    
GRANT CONNECT, RESOURCE TO BABYFISH_DISTINCT_LIMIT;
